#!/bin/bash

if lhs2TeX Main.lhs > main.tex
then

if echo q | pdflatex main.tex
then
	bibtex main
	pdflatex main.tex	&& ( grep -s "Rerun to get" main.log && pdflatex main.tex || true )

        echo "+++ lhs2TeX, pdflatex completed"
else

echo "*** pdflatex failed"

fi

else

echo "*** lhs2tex failed"

fi
