-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Feb 11, 2020 at 04:16 PM
-- Server version: 10.1.37-MariaDB
-- PHP Version: 7.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u459209384_ceur`
--

-- --------------------------------------------------------

--
-- Table structure for table `tblPwdReset`
--

CREATE TABLE `tblPwdReset` (
  `email` varchar(30) COLLATE utf8_bin NOT NULL,
  `reset_code` varchar(75) COLLATE utf8_bin NOT NULL DEFAULT '',
  `reset_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dumping data for table `tblPwdReset`
--

INSERT INTO `tblPwdReset` (`email`, `reset_code`, `reset_time`) VALUES
('inboxofvishnu@gmail.com', '654a6ba5f030175451a961525f2495abcbfe4b7c', '2019-07-15 21:51:55');

-- --------------------------------------------------------

--
-- Table structure for table `tblUsers`
--

CREATE TABLE `tblUsers` (
  `user_id` int(10) UNSIGNED NOT NULL,
  `first_name` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '',
  `last_name` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '',
  `email` varchar(30) COLLATE utf8_bin NOT NULL DEFAULT '',
  `password` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '',
  `login_type` enum('GOOGLE','FACEBOOK','EMAIL') COLLATE utf8_bin NOT NULL DEFAULT 'EMAIL',
  `auth_id` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `email_verification_code` varchar(75) COLLATE utf8_bin NOT NULL DEFAULT '',
  `status` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dumping data for table `tblUsers`
--

INSERT INTO `tblUsers` (`user_id`, `first_name`, `last_name`, `email`, `password`, `login_type`, `auth_id`, `email_verification_code`, `status`) VALUES
(9, 'TEST', 'USER', 'testerusre@testing.de', '7288edd0fc3ffcbe93a0cf06e3568e28521687bc', 'EMAIL', '', '', 0),
(11, 'test', 'usering', 'testinguser123@123.de', '7288edd0fc3ffcbe93a0cf06e3568e28521687bc', 'EMAIL', '', '', 0),
(31, 'Vishnu', 'N', 'inboxofvishnu@gmail.com', '', 'GOOGLE', '116535118994148985430', '', 0),
(41, 'CEUR', 'USER', 'ceuruser@gmail.com', '3015e50d3730720c810293d77dd224231f05935b', 'EMAIL', '', '', 1),
(46, 'Vishnu', 'Menon', 'vishnumenon888@gmail.com', '7c4a8d09ca3762af61e59520943dc26494f8941b', 'EMAIL', '', '', 1);

-- --------------------------------------------------------

--
-- Table structure for table `tblWorkshops`
--

CREATE TABLE `tblWorkshops` (
  `rec_id` int(10) UNSIGNED NOT NULL,
  `user_id` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `json_data` text COLLATE utf8_bin NOT NULL,
  `created_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dumping data for table `tblWorkshops`
--

INSERT INTO `tblWorkshops` (`rec_id`, `user_id`, `json_data`, `created_time`) VALUES
(2, 29, '[{\"title\":{\"id\":\"ASD\",\"acronym\":\"ASD\",\"full\":\"ASD\",\"volume\":\"ASD\"},\"number\":\"vol-F\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"av\",\"location\":\"ASD\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2019-07-11\",\"conference\":{\"acronym\":\"ASD\",\"full\":\"SDF\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"DFG\",\"affiliation\":\"GF\",\"country\":\"Argentina\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},{\"name\":\"HJK\",\"affiliation\":\"HJK\",\"country\":\"Botswana\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d383e45bc18c\"}]', '2019-07-24 14:22:10'),
(3, 30, '[{\"title\":{\"id\":\"123\",\"acronym\":\"TEST\",\"full\":\"TEST\",\"volume\":\"TESt\"},\"number\":\"vol-123\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"\",\"full\":\"\",\"homepage\":\"\"},\"editors\":[{\"name\":\"TEST\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d3883a96451c\"}]', '2019-07-24 16:14:06'),
(4, 30, '[{\"title\":{\"id\":\"1212\",\"acronym\":\"TEST\",\"full\":\"FULLTITLEWORKSHOP\",\"volume\":\"WORKSHOPSDA\"},\"number\":\"vol-1212\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"\",\"full\":\"\",\"homepage\":\"\"},\"editors\":[{\"name\":\"TEST\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d2ddd387acac\"}]', '2019-07-27 21:40:45'),
(5, 31, '[{\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"FULLTITLEOFVOLUME\",\"volume\":\"TEST\"},\"number\":\"vol-123\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d3cc92595e9c\"}]', '2019-07-28 13:17:49'),
(6, 31, '[{\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d42134ba3fae\"}]', '2019-07-31 22:25:20'),
(7, 31, '[{\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d64efe3b0e1c\"}]', '2019-08-27 08:55:23'),
(8, 32, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"ASDASD\",\"acronym\":\"ASDASDADS\",\"full\":\"asas\",\"volume\":\"ASDASD\"},\"number\":\"vol-asas\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"as\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2019-08-14\",\"conference\":{\"acronym\":\"3DV\",\"full\":\"International Conference on 3D Vision 3DV\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"asd\",\"affiliation\":\"asd\",\"country\":\"Angola\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d652612a5a17\"}]', '2019-08-27 12:46:45'),
(9, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d64efe3b0e1c\"}]', '2019-08-28 08:39:23'),
(10, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 14:38:56'),
(11, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 15:10:45'),
(12, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 15:15:08'),
(13, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 15:15:48'),
(14, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 15:17:14'),
(15, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 15:18:35'),
(16, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 15:19:39'),
(17, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d711de60d390\"}]', '2019-09-05 15:23:30'),
(18, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d7128aedd6d0\"}]', '2019-09-05 15:24:35'),
(19, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d761dfe7e19b\"}]', '2019-09-09 09:40:22'),
(20, 32, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"ASDASD\",\"acronym\":\"ASDASDADS\",\"full\":\"asas\",\"volume\":\"ASDASD\"},\"number\":\"ASDASD\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"as\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2019-08-14\",\"conference\":{\"acronym\":\"3DV\",\"full\":\"International Conference on 3D Vision 3DV\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"asd\",\"affiliation\":\"asd\",\"country\":\"Angola\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d764e2eaa10c\"}]', '2019-09-09 13:06:13'),
(21, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d7652acaff13\"}]', '2019-09-09 13:25:07'),
(22, 32, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"ASDASD\",\"acronym\":\"ASDASDADS\",\"full\":\"asas\",\"volume\":\"ASDASD\"},\"number\":\"ASDASD\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"as\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2019-08-14\",\"conference\":{\"acronym\":\"3DV\",\"full\":\"International Conference on 3D Vision 3DV\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"asd\",\"affiliation\":\"asd\",\"country\":\"Angola\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d76585edafbf\"}]', '2019-09-09 13:56:43'),
(23, 32, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"ASDASD\",\"acronym\":\"ASDASDADS\",\"full\":\"asas\",\"volume\":\"ASDASD\"},\"number\":\"ASDASD\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"as\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2019-08-14\",\"conference\":{\"acronym\":\"3DV\",\"full\":\"International Conference on 3D Vision 3DV\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"asd\",\"affiliation\":\"asd\",\"country\":\"Angola\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d8e41b048090\"}]', '2019-09-27 17:07:10'),
(24, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d8fc28e3fd25\"}]', '2019-09-28 20:29:08'),
(25, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d8fc28e3fd25\"}]', '2019-09-28 20:40:17'),
(26, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"TESt\",\"acronym\":\"TEST\",\"full\":\"TESt\",\"volume\":\"TEST\"},\"number\":\"vol-21\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"DCC\",\"full\":\"ACM SIGCOMM Workshop onDistributed Cloud Computing\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TESt\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"nl-srv-web223.main-hosting.eu5d8fc28e3fd25\"}]', '2019-09-29 06:18:55'),
(27, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5db6b819ad41b\"}]', '2019-10-28 12:03:21'),
(28, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd508b47f4c\"}]', '2019-11-02 10:48:53'),
(29, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 12:36:55'),
(30, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 12:39:27'),
(31, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:27:46'),
(32, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:29:47'),
(33, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:30:26'),
(34, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:30:57'),
(35, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:31:46'),
(36, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:34:11'),
(37, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:35:25'),
(38, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:36:55'),
(39, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:37:59'),
(40, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:41:29'),
(41, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:43:03'),
(42, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:46:00'),
(43, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dbd4efcec792\"}]', '2019-11-03 13:49:54'),
(44, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dcd315d070e5\"}]', '2019-11-14 11:50:15'),
(45, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dcd315d070e5\"}]', '2019-11-14 12:19:30'),
(46, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dcd315d070e5\"}]', '2019-11-18 10:51:54'),
(47, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dcd315d070e5\"}]', '2019-11-18 11:59:24'),
(48, 40, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"foobar\",\"acronym\":\"FOOBAR\",\"full\":\"24th international workshop on bargaining for food \",\"volume\":\"Bargaining for food\"},\"number\":\"vol-123\",\"homepage\":\"http://foobar2013.org\",\"language\":\"en\",\"location\":\"Bremen,Germany\",\"locationlink\":\"http://en.wikipedia.org/wiki/Bremen\",\"date\":\"2019-11-30\",\"conference\":{\"acronym\":\"GSCL\",\"full\":\"German Society for Computational Linguistics\",\"homepage\":\"https://gscl.org/en\"},\"editors\":[{\"name\":\"Alice Carroll\",\"affiliation\":\"University of Wonders\",\"country\":\"United Kingdom of Great Britain and Northern Ireland\",\"homepage\":\"www.alicecarroll.com\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dd7b682c8c8b\"}]', '2019-11-22 11:32:46'),
(49, 40, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"foobar\",\"acronym\":\"FOOBAR\",\"full\":\"24th international workshop on bargaining for food \",\"volume\":\"Bargaining for food\"},\"number\":\"Bargaining for food\",\"homepage\":\"http://foobar2013.org\",\"language\":\"en\",\"location\":\"Bremen,Germany\",\"locationlink\":\"http://en.wikipedia.org/wiki/Bremen\",\"date\":\"2019-11-30\",\"conference\":{\"acronym\":\"GSCL\",\"full\":\"German Society for Computational Linguistics\",\"homepage\":\"http://foobar2013.org\"},\"editors\":[{\"name\":\"Alice Carroll\",\"affiliation\":\"University of Wonders\",\"country\":\"United Kingdom of Great Britain and Northern Ireland\",\"homepage\":\"www.alicecarroll.com\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dd7b682c8c8b\"}]', '2019-11-22 12:02:45'),
(50, 41, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"foobar\",\"acronym\":\"FOOBAR\",\"full\":\"24th international workshop on bargaining for food\",\"volume\":\"Bargaining for food\"},\"number\":\"vol-123\",\"homepage\":\"http://foobar2013.org\",\"language\":\"en\",\"location\":\"Bremen, Germany\",\"locationlink\":\"http://en.wikipedia.org/wiki/Bremen\",\"date\":\"2018-11-30\",\"conference\":{\"acronym\":\"CSC\",\"full\":\"ACM Annual Conference on Computer Science\",\"homepage\":\"https://www.acm.org/conferences\"},\"editors\":[{\"name\":\" Alice Carroll\",\"affiliation\":\"University of Wonders\",\"country\":\"United Kingdom of Great Britain and Northern Ireland\",\"homepage\":\" www.alicecarroll.com\"},{\"name\":\"Christoph Lange\",\"affiliation\":\"University of Bonn\",\"country\":\"Germany\",\"homepage\":\"www.langec.wordpress.com\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dd917b85633a\"}]', '2019-11-23 12:37:34'),
(51, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5dd917b85633a\"}]', '2019-11-26 11:44:06'),
(52, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf72ddca55a\"}]', '2019-11-28 08:10:30'),
(53, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:12:25'),
(54, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:17:34'),
(55, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:19:44'),
(56, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:23:00'),
(57, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:28:01'),
(58, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:28:59'),
(59, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:29:28'),
(60, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:34:24'),
(61, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:37:35'),
(62, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:40:09'),
(63, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf73548e1da\"}]', '2019-11-28 08:49:02'),
(64, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf7c5f449cf\"}]', '2019-11-28 08:51:01'),
(65, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf7c5f449cf\"}]', '2019-11-28 09:35:24'),
(66, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf8afe8b67a\"}]', '2019-11-28 09:53:26'),
(67, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf8afe8b67a\"}]', '2019-11-28 09:53:56'),
(68, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf8afe8b67a\"}]', '2019-11-28 10:08:10'),
(69, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:15:48'),
(70, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:16:35');
INSERT INTO `tblWorkshops` (`rec_id`, `user_id`, `json_data`, `created_time`) VALUES
(71, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:26:45'),
(72, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:31:48'),
(73, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:36:49'),
(74, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:37:38'),
(75, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:38:31'),
(76, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:43:12'),
(77, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddf903e39dbd\"}]', '2019-11-28 10:44:14'),
(78, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5ddfae5d6b56d\"}]', '2019-11-28 12:24:19'),
(79, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5de0424eb8a49\"}]', '2019-11-28 22:55:47'),
(80, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 01:21:22'),
(81, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 01:24:07'),
(82, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 01:26:58'),
(83, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 01:30:31'),
(84, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 01:33:43'),
(85, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 01:37:03'),
(86, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 01:42:59'),
(87, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e40a196eebb3\"}]', '2020-02-10 02:02:09'),
(88, 31, '[{\"workshop_series\":\"AIIA\",\"title\":{\"id\":\"12313\",\"acronym\":\"TEST\",\"full\":\"222FULLTITLEOFVOLUME222\",\"volume\":\"TEST\"},\"number\":\"TEST\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\",\"language\":\"ab\",\"location\":\"TEST\",\"locationlink\":\"https://vishnunandakumar.com/publishPage.php\",\"date\":\"2002-02-02\",\"conference\":{\"acronym\":\"TEST\",\"full\":\"TESt\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"},\"editors\":[{\"name\":\"TESt\",\"affiliation\":\"TEST\",\"country\":\"Afghanistan\",\"homepage\":\"https://vishnunandakumar.com/publishPage.php\"}],\"fileName\":\"kinns-HP-Pavilion-Laptop-15-ck0xx5e4136f172aaa\"}]', '2020-02-10 11:56:56');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tblPwdReset`
--
ALTER TABLE `tblPwdReset`
  ADD PRIMARY KEY (`email`);

--
-- Indexes for table `tblUsers`
--
ALTER TABLE `tblUsers`
  ADD PRIMARY KEY (`user_id`),
  ADD KEY `email` (`email`);

--
-- Indexes for table `tblWorkshops`
--
ALTER TABLE `tblWorkshops`
  ADD PRIMARY KEY (`rec_id`),
  ADD KEY `user_id` (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tblUsers`
--
ALTER TABLE `tblUsers`
  MODIFY `user_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=47;

--
-- AUTO_INCREMENT for table `tblWorkshops`
--
ALTER TABLE `tblWorkshops`
  MODIFY `rec_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=89;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
