#!/bin/sh

texify()
{
  sed 's/\_neg\_flip/^~^/g' \
    | sed 's/\_neg/^~/g' \
    | sed 's/\_flip/^^/g' \
    | sed 's/right\_//g'
}

echo '\\begin{code}' > equivalences.tex
cat implications \
  | grep ' <=> ' \
  | texify \
  | column -t \
  >> equivalences.tex
echo '\\end{code}' >> equivalences.tex

echo '\\begin{code}' > implications.tex
cat implications \
  | grep ' <= ' \
  | texify \
  | sed 's/<=/X<=/g' \
  | column -t -sX \
  >> implications.tex
echo '\\end{code}' >> implications.tex

N=`grep ' <= ' implications | wc -l`
N2=`expr $N / 2`
N1=`expr $N - $N2`

cat implications \
  | grep ' <= ' \
  | texify \
  | sed 's/<=/X<=/g' \
  | head "-$N1" \
  > impl-col1
  
cat implications \
  | grep ' <= ' \
  | texify \
  | sed 's/<=/X<=/g' \
  | tail "-$N2" \
  | sed 's/^/X/' \
  > impl-col2

paste impl-col1 impl-col2 \
  | sed 's/\t/ /g' \
  > impl-cols
  
echo '\\begin{code}' > implications2.tex
column -t -sX impl-cols >> implications2.tex
echo '\\end{code}' >> implications2.tex

